# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Mi Primer Pipeline

on:
  push:
    branches: [ main ]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    - name: Decir hola
      run: echo "¡Hola! Mi primer pipeline funciona 🎉"
